##################################
### DO NOT EDIT THIS FILE      ###
###                            ###
### CT100 boot.py V0.2         ###
### Last Updated               ###
### Simon Maselli              ###
### 25 July 2017               ###
###                            ###
### Copyright Minnovation 2017 ###
##################################


### Turn off LED & Wifi to save power
w = WLAN()
w.deinit() ##Switch Off WLAN
pycom.heartbeat(False)

################# SIGFOX ###################
#from network import Sigfox
#sigfox = Sigfox(mode=Sigfox.SIGFOX, rcz=Sigfox.RCZ4)
#ss = socket.socket(socket.AF_SIGFOX, socket.SOCK_RAW)
#ss.setblocking(True)

################# LORA #####################
#from network import LoRa
#lora = LoRa(mode=LoRa.LORA, region=LoRa.AU915)
#sl = socket.socket(socket.AF_LORA, socket.SOCK_RAW)
#sl.setblocking(False)
